### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by WambuaSimon** [Ian-Cornelius/ATOnDroid#4]
Server doesnt appear as a module under app

**Comment by Ian-Cornelius** [comment]
That is because you did not add it as a module. To correct this, go to **File** **New** **New Module** and select Java library. Provide a name and a class name. 

Now you'll have your module. However, you'll need to copy the code in MyServer to the java class of this module and do the same for the server module dependencies.

Finally, before running the server, click on the drop-down next to the green run button. Select **Edit configurations**, click on the green plus sign at the top left and select application.  Provide a name, set the class as the java class under your module (Fully qualified using the package name) and select the module under the **select module** drop down.

Click on ok. You will see your server module added in the drop down. If you try to run it, you may get a **class not found error**. Redo the previous step (in Edit Configurations), and run the server again. The error will be gone. 

Hope that solves your problem. Reach out in case it doesn't.

Thanks!
